[project]
name = "zotero-pdf2zh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "babeldoc>=0.5.11",
    "flask>=3.1.2",
    "pdf2zh-next>=2.6.4",
    "pypdf>=6.1.1",
]
